askcomrade/urls.py
from django.conf.urls import include, url
from django.contrib import admin
admin.autodiscover()
from django.views.generic import TemplateView
from askcomrade.server import views, ajax, search, moderate, api, orcid
from askcomrade.apps.posts.views import NewAnswer, NewPost, EditPost, external_post_handler
from askcomrade.apps.users.views import external_logout, external_login, CaptchaView, DigestManager, unsubscribe
from askcomrade.apps.planet.views import BlogPostList

urlpatterns = [
    url(r'^$', views.PostList.as_view(), name="home"),
    url(r'^t/$', views.TagList.as_view(), name="tag-list"),
    url(r'^b/(?P<pk>\d+)/$', views.BadgeView.as_view(), name="badge-view"),
    url(r'^b/list/$', views.BadgeList.as_view(), name="badge-list"),
    url(r'^t/(?P<topic>.+)/$', views.PostList.as_view(), name="topic-list"),
    url(r'^user/list/$', views.UserList.as_view(), name="user-list"),
    url(r'^u/(?P<pk>\d+)/$', views.UserDetails.as_view(), name="user-details"),
    url(r'^u/edit/(?P<pk>\d+)/$', views.EditUser.as_view(), name="user-edit"),
    url(r'^p/(?P<pk>\d+)/$', views.PostDetails.as_view(), name="post-details"),
    url(r'^local/sub/(?P<pk>\d+)/(?P<type>\w+)/$', views.ChangeSub.as_view(), name="change-sub"),
    url(r'^p/new/post/$', views.RateLimitedNewPost.as_view(), name="new-post"),
    url(r'^p/new/external/post/$', external_post_handler, name="new-external-post"),
    url(r'^p/new/answer/(?P<pid>\d+)/$', views.RateLimitedNewAnswer.as_view(post_type="answer"), name="new-answer"),
    url(r'^p/new/comment/(?P<pid>\d+)/$', views.RateLimitedNewAnswer.as_view(post_type="comment"), name="new-comment"),
    url(r'^p/edit/(?P<pk>\d+)/$', EditPost.as_view(), name="post-edit"),
    url(r'^local/messages/$', views.MessageList.as_view(), name="user-messages"),
    url(r'^local/votes/$', views.VoteList.as_view(), name="user-votes"),
    url(r'^local/moderate/post/(?P<pk>\d+)/$', moderate.PostModeration.as_view(), name="post-moderation"),
    url(r'^local/moderate/user/(?P<pk>\d+)/$', moderate.UserModeration.as_view(), name="user-moderation"),
    url(r'^site/login/$', external_login, name="login"),
    url(r'^site/logout/$', external_logout, name="logout"),
    url(r'^accounts/signup/$', CaptchaView.as_view(), name="signup"),
    url(r'^local/email/', views.email_handler, name="email-handler"),
    url(r'^local/search/page/', search.Search.as_view(), name="search-page"),
    url(r'^local/search/title/', search.search_title, name="search-title"),
    url(r'^digest/manage/', DigestManager.as_view() , name="digest_manage"),
    url(r'^digest/unsubscribe/(?P<uuid>\w+)/', unsubscribe , name="digest_unsubscribe"),
    url(r'^local/search/tags/', search.suggest_tags, name="suggest-tags"),
    url(r'^planet/$', BlogPostList.as_view(), name="planet"),
    url(r'^x/vote/$', ajax.vote_handler, name="vote-submit"),
    # url(r'^accounts/social/orcid/import/$', orcid.import_bio, name="orcid-import"),
    url(r'^accounts/', include('allauth.urls')),

    # Redirecting old posts urls from previous versions of Askcomrade
    url(r'^post/redirect/(?P<pid>\d+)/$', views.post_redirect),
    url(r'^post/show/(?P<pid>\d+)/$', views.post_redirect),
    url(r'^post/show/(?P<pid>\d+)/([-\w]+)/$', views.post_redirect),
    url(r'^questions/(?P<pid>\d+)/$', views.post_remap_redirect),
    url(r'^questions/(?P<pid>\d+)/([-\w]+)/$', views.post_remap_redirect),
    url(r'^questions/tagged/(?P<tag>.+)/$',views.tag_redirect),

    # Api.
    url(r'^api/traffic/$', api.traffic, name='api-traffic'),
    url(r'^api/user/(?P<id>\d+)/$', api.user_details, name='api-user'),
    url(r'^api/post/(?P<id>\d+)/$', api.post_details, name='api-post'),
    url(r'^api/vote/(?P<id>\d+)/$', api.vote_details, name='api-vote'),
    url(r'^api/stats/day/(?P<day>\d+)/$', api.daily_stats_on_day, name='api-stats-on-day'),
    url(r'^api/stats/date/(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/$',
        api.daily_stats_on_date, name='api-stats-on-date'),

    url(r'^admin/', include(admin.site.urls)),

     # Local robots.txt.
    url(r'^robots\.txt$', TemplateView.as_view(template_name="robots.txt", content_type='text/plain'), name='robots'),

]


from askcomrade.server.feeds import LatestFeed, TagFeed, UserFeed, PostFeed, PostTypeFeed, PlanetFeed

# Adding the RSS related urls.
urlpatterns += [
    url(r'^info/rss/$', views.RSS.as_view(), name='rss'),

    url(r'^feeds/latest/$', LatestFeed(), name='latest-feed'),

    url(r'^feeds/tag/(?P<text>[\w\-_\+!]+)/$', TagFeed(), name='tag-feed'),
    url(r'^feeds/user/(?P<text>[\w\-_\+!]+)/$', UserFeed(), name='user-feed'),
    url(r'^feeds/post/(?P<text>[\w\-_\+!]+)/$', PostFeed(), name='post-feed' ),
    url(r'^feeds/type/(?P<text>[\w\-_\+!]+)/$', PostTypeFeed(), name='post-type'),
    url(r'^feeds/planet/$', PlanetFeed(), name='planet-feed'),
]

urlpatterns += [
    url(r'^info/(?P<slug>\w+)/$', views.FlatPageView.as_view(), name='flatpage'),
    url(r'^info/update/(?P<pk>\d+)/$', views.FlatPageUpdate.as_view(), name='flatpage-update'),
]

# Adding the sitemap.
# urlpatterns += [
#     url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': search.sitemaps})
# ]

askcomrade/apps/users/models.py
from __future__ import print_function, unicode_literals, absolute_import, division
import logging
from django import forms
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.admin import UserAdmin
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from askcomrade.apps import util
import bleach
from django.core.urlresolvers import reverse
from django.contrib.sites.models import Site
from datetime import timedelta
from django.core.mail import send_mail
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.contrib.auth.models import BaseUserManager
from askcomrade import const
from django.db.models.signals import post_save
from askcomrade.apps.messagez.models import Message, MessageBody
from askcomrade.apps.util import html
from askcomrade.const import now
import random
from django.dispatch import receiver


ALLOWED_TAGS = bleach.ALLOWED_TAGS + settings.ALLOWED_TAGS
ALLOWED_STYLES = bleach.ALLOWED_STYLES + settings.ALLOWED_STYLES
ALLOWED_ATTRIBUTES = dict(bleach.ALLOWED_ATTRIBUTES)
ALLOWED_ATTRIBUTES.update(settings.ALLOWED_ATTRIBUTES)

logger = logging.getLogger(__name__)

class Tag(models.Model):
    name = models.TextField(max_length=50, db_index=True)

MESSAGE_PREF_MAP = dict(
    local=const.LOCAL_MESSAGE, default=const.DEFAULT_MESSAGES,
    email=const.EMAIL_MESSAGE, all=const.ALL_MESSAGES,
)
MESSAGE_PREFS = MESSAGE_PREF_MAP.get(settings.DEFAULT_MESSAGE_PREF, const.LOCAL_MESSAGE)





class UserManager(BaseUserManager):
    def create_user(self, email, password=None, **kwargs):
        email = self.normalize_email(email)
        user = self.model(email=email, **kwargs)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, **kwargs):
        user = self.create_user(**kwargs)
        user.is_superuser = True
        user.is_staff = True
        user.save(using=self._db)
        return user


class LocalManager(UserManager):
    def get_users(self, sort, limit, q, user):
        sort = const.USER_SORT_MAP.get(sort, None)
        days = const.POST_LIMIT_MAP.get(limit, 0)

        if q:
            query = self.filter(name__icontains=q)
        else:
            query = self

        if days:
            delta = const.now() - timedelta(days=days)
            query = self.filter(profile__last_login__gt=delta)

        if user.is_authenticated() and user.is_moderator:
            query = query.select_related("profile").order_by(sort)
        else:
            query = query.exclude(status=User.BANNED).select_related("profile").order_by(sort)

        return query


class AbstractEmailUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), max_length=255, unique=True)
    is_staff = models.BooleanField(_('staff status'), default=False,
        help_text=_('Designates whether the user can log into this admin '
                    'site.'))
    is_active = models.BooleanField(_('active'), default=True,
        help_text=_('Designates whether this user should be treated as '
                    'active. Unselect this instead of deleting accounts.'))
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        abstract = True
        ordering = ['email']

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.email

    def email_user(self, subject, message, from_email=None, **kwargs):
        # send_mail(subject, message, from_email, [self.email], **kwargs)
        send_mail(subject, message, from_email, self.email, **kwargs)


class AbstractNamedUser(AbstractEmailUser):
    name = models.CharField(_('name'), max_length=255)

    REQUIRED_FIELDS = ['name']

    class Meta:
        abstract = True
        ordering = ['name', 'email']

    def __str__(self):
        return '{name} <{email}>'.format(
            name=self.name,
            email=self.email,
        )

    def get_full_name(self):
        return self.name

    def get_short_name(self):
        return self.name


class User(AbstractNamedUser):





    USER, MODERATOR, ADMIN, BLOG = range(4)
    TYPE_CHOICES = [(USER, "User"), (MODERATOR, "Moderator"), (ADMIN, "Admin"), (BLOG, "Blog")]

    NEW_USER, TRUSTED, SUSPENDED, BANNED = range(4)
    STATUS_CHOICES = ((NEW_USER, 'New User'), (TRUSTED, 'Trusted'), (SUSPENDED, 'Suspended'), (BANNED, 'Banned'))

    USERNAME_FIELD = 'email'

    objects = LocalManager()

    email = models.EmailField(verbose_name='Email', db_index=True, max_length=255, unique=True)
    name = models.CharField(verbose_name='Name', max_length=255, default="", blank=False)

    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    type = models.IntegerField(choices=TYPE_CHOICES, default=USER)
    status = models.IntegerField(choices=STATUS_CHOICES, default=NEW_USER)
    new_messages = models.IntegerField(default=0)
    badges = models.IntegerField(default=0)
    score = models.IntegerField(default=0)
    activity = models.IntegerField(default=0)
    flair = models.CharField(verbose_name='Flair', max_length=15, default="")
    site = models.ForeignKey(Site, null=True)

    @property
    def is_moderator(self):
        if self.is_authenticated():
            return self.type == User.MODERATOR or self.type == User.ADMIN
        else:
            return False

    @property
    def is_administrator(self):
        if self.is_authenticated():
            return self.type == User.ADMIN
        else:
            return False

    @property
    def is_trusted(self):
        return self.status == User.TRUSTED

    @property
    def is_suspended(self):
        return self.status == User.SUSPENDED or self.status == User.BANNED

    def get_full_name(self):
        return self.name or self.email

    def get_short_name(self):
        return self.name or self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    def save(self, *args, **kwargs):
        if not self.name:
            self.name = self.email.split("@")[0]

        super(User, self).save(*args, **kwargs)

    @property
    def scaled_score(self):
        return self.score * 10

    def __str__(self):
        return "%s: %s (%s)" % (self.name, self.email, self.id)

    def get_absolute_url(self):
        url = reverse("user-details", kwargs=dict(pk=self.id))
        return url


class EmailList(models.Model):
    email = models.EmailField(verbose_name='Email', db_index=True, max_length=255, unique=True)
    type = models.IntegerField(default=0)
    active = models.BooleanField(default=True)
    date = models.DateTimeField(auto_created=True)



class Profile(models.Model):
    LOCAL_MESSAGE, EMAIL_MESSAGE = const.LOCAL_MESSAGE, const.EMAIL_MESSAGE
    NO_DIGEST, DAILY_DIGEST, WEEKLY_DIGEST, MONTHLY_DIGEST = range(4)
    TYPE_CHOICES = const.MESSAGING_TYPE_CHOICES

    DIGEST_CHOICES = [(NO_DIGEST, 'Never'), (DAILY_DIGEST, 'Daily'),
                      (WEEKLY_DIGEST, 'Weekly'), (MONTHLY_DIGEST, 'Monthly')]
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    uuid = models.CharField(null=False, db_index=True, unique=True, max_length=255)
    last_login = models.DateTimeField()
    date_joined = models.DateTimeField()
    location = models.CharField(default="", max_length=255, blank=True)
    website = models.URLField(default="", max_length=255, blank=True)
    scholar = models.CharField(default="", max_length=255, blank=True)
    twitter_id = models.CharField(default="", max_length=255, blank=True)
    my_tags = models.TextField(default="", max_length=255, blank=True)
    info = models.TextField(default="", null=True, blank=True)
    message_prefs = models.IntegerField(choices=TYPE_CHOICES, default=MESSAGE_PREFS)
    flag = models.IntegerField(default=0)
    watched_tags = models.CharField(max_length=100, default="", blank=True)
    tags = models.ManyToManyField(Tag, blank=True, )
    digest_prefs = models.IntegerField(choices=DIGEST_CHOICES, default=WEEKLY_DIGEST)
    opt_in = models.BooleanField(default=False)

    def parse_tags(self):
        return util.split_tags(self.tag_val)

    def clear_data(self):
        self.website = self.twitter_id = self.info = self.location = ''
        self.save()

    def add_tags(self, text):
        text = text.strip()
        self.tag_val = bleach.clean(text, tags=[], attributes=[], styles={}, strip=True)
        self.tags.clear()
        tags = [Tag.objects.get_or_create(name=name)[0] for name in self.parse_tags()]
        self.tags.add(*tags)

    def save(self, *args, **kwargs):
        self.info = bleach.clean(self.info, tags=ALLOWED_TAGS,
                                 attributes=ALLOWED_ATTRIBUTES, styles=ALLOWED_STYLES)
        self.location = self.location.strip()
        if not self.id:
            try:
                self.uuid = util.make_uuid()
            except:
                x = random.getrandbits(256)
                return x
            self.date_joined = self.date_joined or now()
            self.last_login = self.date_joined

        super(Profile, self).save(*args, **kwargs)

    def __str__(self):
        return "%s" % self.user.name

    @property
    def filled(self):
        has_location = bool(self.location.strip())
        has_info = bool(self.info.strip())
        return has_location and has_info

    @staticmethod
    def auto_create(sender, instance, created, *args, **kwargs):
        pass
        # "Should run on every user creation."
        # if created:

askcomrade/server/templates/server_tags/comment_body.html
{% load server_tags %}
{#<a name="{{ post.id }}"></a>#}
{#<div class="entry {{ post.get_status_display }}  clearfix">#}
{##}
{#    <div class="comment vote-box" data-post_id="{{ post.id }}">#}
{#        <div class="vote mark {{ post.has_upvote|on }} " data-type="vote" title="Upvote!">#}
{#            <i class="fa fa-thumbs-o-up fa-1x"></i></div>#}
{#        <div class="count">{{ post.vote_count|show_nonzero }}</div>#}
{#    </div>#}

   {{ post.html }}

{#    {% post_actions post user "REPLY" %}#}

{#</div>#}

askcomrade/server/templates/server_tags/nav_bar.html
{% load static %}
{% load server_tags %}

<div class="row visible-sm visible-xs">

    <div class="col-xs-4">
        <div class="btn-group">
            <button type="button" class="btn btn-primary dropdown-toggle btn-xs" data-toggle="dropdown">
                {% if topic %} {{ topic }} {% else %} View Posts {% endif %}
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
                <li><a href="{% url 'planet' %}">Planet</a></li>
                <li><a href="{% url 'tag-list' %}">All &raquo;</a></li>
            </ul>
        </div>
    </div>

        <div class="col-xs-4 text-center" style="margin-bottom:5px">
        <a role="button" class="btn btn-warning btn-xs" href="{% url 'home' %}">
            <i class="fa fa-star fa-1x"></i> Home
        </a>

    </div>

    <div class="col-xs-4">
        <div class="btn-group pull-right btn-xs">

            {% if user.is_authenticated %}
                <button type="button" class="btn btn-success dropdown-toggle btn-xs" data-toggle="dropdown">
                    <i class="fa fa-user"></i> You
                    <span class="badge">
                        {% get_cuont COUNTS 'messages' %}
                    </span>
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu">
                    <li>
                        <a href="{% url 'topic-list' topic='myposts' %}"><i class="fa fa-comments"></i> My Posts</a>
                    </li>
                    <li>
                        <a href="{% url 'user-messages' %}"><i class="fa fa-envelope"></i> My Messages
                         <span class="badge">2
                             {% get_cuont COUNTS 'messages' %}
                         </span> </a>

                    <li>
                        <a href="{% url 'topic-list' topic='bookmarks' %}"><i class="fa fa-book"></i> My Bookmarks</a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="{% url 'new-post' %}"><i class="fa fa-plus"></i> New Post</a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="{% url 'logout' %}"><i class="fa fa-sign-out"></i> Log Out</a>
                    </li>
                </ul>
            {% else %}
                <div>
                    <a class="btn btn-primary active" role="button" href="{% url 'login' %}">
                        <i class="fa fa-user fa-1x"></i> Log In
                    </a>
                </div>
            {% endif %}
        </div>
    </div>
</div>
<div class="col-md-9 top text-center">
    <h3>Welcome to AskComrade</h3>
    <b><a href="{% url 'signup' %}">
        <div><i class="fa fa-arrow-circle-up fa-1x"></i></div>
        <div>Sign Up</div>
    </a></b>
</div>

askcomrade/server/templates/server_tags/page_bar.html
{% load humanize %}


<div class="text-center">
        <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}&sort={{ sort }}&limit={{ limit }}&q={{ q }}">&lt;prev</a>
        {% else %}
            &lt;prev
        {% endif %}
            <span class="current">
              &bull; {{ page_obj.paginator.count|intcomma }} results &bull;
                page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }} &bull;
        </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}&sort={{ sort }}&limit={{ limit }}&q={{ q }}">next &gt;</a>
            {% else %}
                next &gt;
            {% endif %}
        </span>
</div>

askcomrade/server/templates/server_tags/page_bar_sort_posts.html
{% load humanize %}

<div class="row pagebar">
    <div class="col-sm-3">


        <div class="btn-group visible-lg visible-md">
            <button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown">
                Limit to: {{ limit }} <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
                {% for field in date_fields %}
                    <li><a href="?sort={{ sort }}&limit={{ field }}&q={{ q }}">{{ field }}</a></li>
                {% endfor %}
            </ul>
        </div>

    </div>

    <div class="cold-sm-12 col-md-6 text-center ">

        <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}&sort={{ sort }}&limit={{ limit }}&q={{ q }}">&lt;prev</a>
        {% else %}
            &lt;prev
        {% endif %}

            <span class="current">
              &bull; {{ page_obj.paginator.count|intcomma }} results &bull;
                page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }} &bull;
        </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}&sort={{ sort }}&limit={{ limit }}&q={{ q }}">next &gt;</a>
            {% else %}
                next &gt;
            {% endif %}
        </span>
    </div>

    <div class="col-sm-3 visible-lg visible-md">
        <div class="btn-group pull-right">
            <button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown">
                Sort by: {{ sort }} <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
                {% for field in sort_fields %}
                    <li><a href="?sort={{ field }}&limit={{ limit }}&q={{ q }}">{{ field }}</a></li>
                {% endfor %}
            </ul>
        </div>

    </div>

</div>

askcomrade/server/templates/server_tags/post_actions.html
{% load server_tags %}
{% load humanize %}
<div class="post-action">

    <span class="label label-default add-comment" data-value="{{ post.id }}" id="C{{ post.id }}">ADD {{ label }}</span>

    &bull; <a href="{{ post.get_absolute_url }}">link</a>
    {% if post.is_editable %}
        &bull; <a href="{% url 'post-edit' post.id %}" id="E{{ post.id }}">edit</a>
        &bull; <a class="mod-post" data-value="{{ post.id }}" id="M{{ post.id }}">moderate</a>
        {% if post.book_count %} &bull; {{ post.book_count }} bookmark{{ post.book_count|pluralize }}{% endif %}
    {% endif %}

    {% if post.is_toplevel %}
        {#  Produce the Follow button #}
        &bull;

        <div class="btn-group">
            <button type="button" class="btn btn-default btn-xs dropdown-toggle" id="F{{ post.id }}" data-toggle="dropdown">
                {% if post.sub %}
                    Follow via {{ post.sub.get_type_display }}
                {% else %}
                    Not following
                {% endif %}
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu dropup" role="menu">

                <li><a href="{% url 'change-sub' pk=post.id type='local' %}">Follow via messages</a></li>
                <li><a href="{% url 'change-sub' pk=post.id type='email' %}">Follow via email</a></li>
                <li><a href="{% url 'change-sub' pk=post.id type='nofollow' %}">Do not follow</a></li>
            </ul>
        </div>
    {% endif %}

    <span class="userlink muted">
            {% if post.creation_date != post.lastedit_date %}
            modified {{ post.lastedit_date|time_ago }}
            {%  if post.author != post.lastedit_user %}
                by {% userlink post.lastedit_user %}
            {%  endif %}
            &bull;
        {% endif %}
        written <span itemprop="dateCreated" content="{{ post.creation_date|date:'c' }}">
        {{ post.creation_date|time_ago }}</span> by {% userlink post.author %}
    </span>
</div>

askcomrade/server/templates/server_tags/post_count_box.html
{# Renders the countbox for each post #}
{% load server_tags %}
{% load humanize %}
<div class="post-row {{ post.get_type_display }} {{ post.get_status_display }}">

    <div class="count-box visible-lg visible-md">
        <div class="box vote">
            {% if post.is_toplevel %}
                <div class="c">{{ post.thread_score }}</div>
                <div class="t">vote{{ post.thread_score|pluralize }}</div>
            {% else %}
                <div class="c">{{ post.vote_count }}</div>
                <div class="t">vote{{ post.vote_count|pluralize }}</div>
            {% endif %}
        </div>
        <div class="box {% boxclass post.root %}">
            <div class="c">{{ post.root.reply_count }}</div>
            <div class="t">answer{{ post.root.reply_count|pluralize }}</div>
        </div>
        <div class="box view">
{#            <div class="c">{{ post.root.view_count }}</div>#}
            <div class="c">{{ post.root.view_count|bignum }}</div>
            <div class="t">views</div>
        </div>
        {% if post.subs_count > 4 %}
            <div class="book_count text-center">
                {{ post.subs_count }} follow
            </div>
        {% endif %}
    </div>

{#     small devices #}
    <div class="count-box-sm visible-sm visible-xs">
        <div class="box {% boxclass post.root %}">
            <div class="c">{{ post.root.reply_count }}</div>
            <div class="t">answer{{ post.reply_count|pluralize }}</div>
        </div>
    </div>

    <div class="title-box clearfix">
        <div class="post-title">
            {% if post.type != 0 %}
                {{ post.get_type_display }}:
            {% endif %}
            <a href="{{ post.get_absolute_url }}">{{ post.get_title }}</a>
        </div>

        {% if context %}
            <div class="context">... {{ context|safe }} ...</div>
        {% endif %}

        <div class="clearfix">

            <span class="tags tag-pad visible-lg visible-md">
            {% for tag in post.tag_set.all %}
                <a class="tag" href="/t/{{ tag.name }}/">{{ tag.name }}</a>
            {% endfor %}
            </span>

            <span class="userlink text-right muted">
               written {{ post.creation_date|time_ago }} by
                {% userlink post.author %}
                {% if post.author != post.lastedit_user %}
                    &bull; updated
                    <span class="ago2">{{ post.lastedit_date|time_ago }}</span> by
                    {% userlink post.lastedit_user %}
                {% endif %}
            </span>
        </div>
    </div>
</div>

askcomrade/server/templates/server_tags/post_user_box.html
{% load humanize %}
{% load server_tags %}

{#  This is very similar to userbox but needs different positioning #}

<div class="col-xs-3 col-md-2 box pull-right text-center visible-lg visible-md">
        <div><a href="{{ user.get_absolute_url }}">
{#isaac           {% gravatar user 82 %}#}
        </a></div>
        <div class="ago">{{ date|time_ago }} by</div>
        <div class="uname">{% userlink user %}</div>
        <div class="loc">{{ user.profile.location }}</div>
</div>

<div class="box text-center visible-sm visible-xs">
    <div class="uname">{% userlink user %} wrote:</div>
</div>

askcomrade/server/templates/server_tags/search_bar.html
<div class="row">
    <div class="col-md-10 col-md-offset-2 searchbar">
        <div  class="col-md-8">
            <input type="text" id="searchform" style="width:100%">
        </div>

        <div class="visible-lg visible-md">
            or &nbsp;<a role="button" class="btn btn-default btn-xs" href="{%  url 'search-page' %}"><i class="fa fa-search"></i>
            Classic search</a>
        </div>

    </div>
</div>

askcomrade/server/templates/server_tags/sidebar_users.html
{% load cache %}
{% load server_tags %}

<div class="recent-posts">
    <ul>
        {% for user in users %}
            <li >
{#isaac               {%  gravatar user 35 %}#}
                &nbsp; {%  userlink user %}
            </li>
        {% endfor %}
    </ul>
</div>