askcomrade/urls.py
from django.conf.urls import include, url
from django.contrib import admin
admin.autodiscover()
from django.views.generic import TemplateView
from askcomrade.server import views, ajax, search, moderate, api, orcid
from askcomrade.apps.posts.views import NewAnswer, NewPost, EditPost, external_post_handler
from askcomrade.apps.users.views import external_logout, external_login, CaptchaView, DigestManager, unsubscribe
from askcomrade.apps.planet.views import BlogPostList

urlpatterns = [
    url(r'^$', views.PostList.as_view(), name="home"),
    url(r'^t/$', views.TagList.as_view(), name="tag-list"),
    url(r'^b/(?P<pk>\d+)/$', views.BadgeView.as_view(), name="badge-view"),
    url(r'^b/list/$', views.BadgeList.as_view(), name="badge-list"),
    url(r'^t/(?P<topic>.+)/$', views.PostList.as_view(), name="topic-list"),
    url(r'^user/list/$', views.UserList.as_view(), name="user-list"),
    url(r'^u/(?P<pk>\d+)/$', views.UserDetails.as_view(), name="user-details"),
    url(r'^u/edit/(?P<pk>\d+)/$', views.EditUser.as_view(), name="user-edit"),
    url(r'^p/(?P<pk>\d+)/$', views.PostDetails.as_view(), name="post-details"),
    url(r'^local/sub/(?P<pk>\d+)/(?P<type>\w+)/$', views.ChangeSub.as_view(), name="change-sub"),
    url(r'^p/new/post/$', views.RateLimitedNewPost.as_view(), name="new-post"),
    url(r'^p/new/external/post/$', external_post_handler, name="new-external-post"),
    url(r'^p/new/answer/(?P<pid>\d+)/$', views.RateLimitedNewAnswer.as_view(post_type="answer"), name="new-answer"),
    url(r'^p/new/comment/(?P<pid>\d+)/$', views.RateLimitedNewAnswer.as_view(post_type="comment"), name="new-comment"),
    url(r'^p/edit/(?P<pk>\d+)/$', EditPost.as_view(), name="post-edit"),
    url(r'^local/messages/$', views.MessageList.as_view(), name="user-messages"),
    url(r'^local/votes/$', views.VoteList.as_view(), name="user-votes"),
    url(r'^local/moderate/post/(?P<pk>\d+)/$', moderate.PostModeration.as_view(), name="post-moderation"),
    url(r'^local/moderate/user/(?P<pk>\d+)/$', moderate.UserModeration.as_view(), name="user-moderation"),
    url(r'^site/login/$', external_login, name="login"),
    url(r'^site/logout/$', external_logout, name="logout"),
    url(r'^accounts/signup/$', CaptchaView.as_view(), name="signup"),
    url(r'^local/email/', views.email_handler, name="email-handler"),
    url(r'^local/search/page/', search.Search.as_view(), name="search-page"),
    url(r'^local/search/title/', search.search_title, name="search-title"),
    url(r'^digest/manage/', DigestManager.as_view() , name="digest_manage"),
    url(r'^digest/unsubscribe/(?P<uuid>\w+)/', unsubscribe , name="digest_unsubscribe"),
    url(r'^local/search/tags/', search.suggest_tags, name="suggest-tags"),
    url(r'^planet/$', BlogPostList.as_view(), name="planet"),
    url(r'^x/vote/$', ajax.vote_handler, name="vote-submit"),
    # url(r'^accounts/social/orcid/import/$', orcid.import_bio, name="orcid-import"),
    url(r'^accounts/', include('allauth.urls')),

    # Redirecting old posts urls from previous versions of Askcomrade
    url(r'^post/redirect/(?P<pid>\d+)/$', views.post_redirect),
    url(r'^post/show/(?P<pid>\d+)/$', views.post_redirect),
    url(r'^post/show/(?P<pid>\d+)/([-\w]+)/$', views.post_redirect),
    url(r'^questions/(?P<pid>\d+)/$', views.post_remap_redirect),
    url(r'^questions/(?P<pid>\d+)/([-\w]+)/$', views.post_remap_redirect),
    url(r'^questions/tagged/(?P<tag>.+)/$',views.tag_redirect),

    # Api.
    url(r'^api/traffic/$', api.traffic, name='api-traffic'),
    url(r'^api/user/(?P<id>\d+)/$', api.user_details, name='api-user'),
    url(r'^api/post/(?P<id>\d+)/$', api.post_details, name='api-post'),
    url(r'^api/vote/(?P<id>\d+)/$', api.vote_details, name='api-vote'),
    url(r'^api/stats/day/(?P<day>\d+)/$', api.daily_stats_on_day, name='api-stats-on-day'),
    url(r'^api/stats/date/(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/$',
        api.daily_stats_on_date, name='api-stats-on-date'),

    url(r'^admin/', include(admin.site.urls)),

     # Local robots.txt.
    url(r'^robots\.txt$', TemplateView.as_view(template_name="robots.txt", content_type='text/plain'), name='robots'),

]


from askcomrade.server.feeds import LatestFeed, TagFeed, UserFeed, PostFeed, PostTypeFeed, PlanetFeed

# Adding the RSS related urls.
urlpatterns += [
    url(r'^info/rss/$', views.RSS.as_view(), name='rss'),

    url(r'^feeds/latest/$', LatestFeed(), name='latest-feed'),

    url(r'^feeds/tag/(?P<text>[\w\-_\+!]+)/$', TagFeed(), name='tag-feed'),
    url(r'^feeds/user/(?P<text>[\w\-_\+!]+)/$', UserFeed(), name='user-feed'),
    url(r'^feeds/post/(?P<text>[\w\-_\+!]+)/$', PostFeed(), name='post-feed' ),
    url(r'^feeds/type/(?P<text>[\w\-_\+!]+)/$', PostTypeFeed(), name='post-type'),
    url(r'^feeds/planet/$', PlanetFeed(), name='planet-feed'),
]

urlpatterns += [
    url(r'^info/(?P<slug>\w+)/$', views.FlatPageView.as_view(), name='flatpage'),
    url(r'^info/update/(?P<pk>\d+)/$', views.FlatPageUpdate.as_view(), name='flatpage-update'),
]

# Adding the sitemap.
# urlpatterns += [
#     url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': search.sitemaps})
# ]

askcomrade/apps/users/models.py
from __future__ import print_function, unicode_literals, absolute_import, division
import logging
from django import forms
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.admin import UserAdmin
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from askcomrade.apps import util
import bleach
from django.core.urlresolvers import reverse
from django.contrib.sites.models import Site
from datetime import timedelta
from django.core.mail import send_mail
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.contrib.auth.models import BaseUserManager
from askcomrade import const
from django.db.models.signals import post_save
from askcomrade.apps.messagez.models import Message, MessageBody
from askcomrade.apps.util import html
from askcomrade.const import now
import random
from django.dispatch import receiver


ALLOWED_TAGS = bleach.ALLOWED_TAGS + settings.ALLOWED_TAGS
ALLOWED_STYLES = bleach.ALLOWED_STYLES + settings.ALLOWED_STYLES
ALLOWED_ATTRIBUTES = dict(bleach.ALLOWED_ATTRIBUTES)
ALLOWED_ATTRIBUTES.update(settings.ALLOWED_ATTRIBUTES)

logger = logging.getLogger(__name__)

class Tag(models.Model):
    name = models.TextField(max_length=50, db_index=True)

MESSAGE_PREF_MAP = dict(
    local=const.LOCAL_MESSAGE, default=const.DEFAULT_MESSAGES,
    email=const.EMAIL_MESSAGE, all=const.ALL_MESSAGES,
)
MESSAGE_PREFS = MESSAGE_PREF_MAP.get(settings.DEFAULT_MESSAGE_PREF, const.LOCAL_MESSAGE)





class UserManager(BaseUserManager):
    def create_user(self, email, password=None, **kwargs):
        email = self.normalize_email(email)
        user = self.model(email=email, **kwargs)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, **kwargs):
        user = self.create_user(**kwargs)
        user.is_superuser = True
        user.is_staff = True
        user.save(using=self._db)
        return user


class LocalManager(UserManager):
    def get_users(self, sort, limit, q, user):
        sort = const.USER_SORT_MAP.get(sort, None)
        days = const.POST_LIMIT_MAP.get(limit, 0)

        if q:
            query = self.filter(name__icontains=q)
        else:
            query = self

        if days:
            delta = const.now() - timedelta(days=days)
            query = self.filter(profile__last_login__gt=delta)

        if user.is_authenticated() and user.is_moderator:
            query = query.select_related("profile").order_by(sort)
        else:
            query = query.exclude(status=User.BANNED).select_related("profile").order_by(sort)

        return query


class AbstractEmailUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), max_length=255, unique=True)
    is_staff = models.BooleanField(_('staff status'), default=False,
        help_text=_('Designates whether the user can log into this admin '
                    'site.'))
    is_active = models.BooleanField(_('active'), default=True,
        help_text=_('Designates whether this user should be treated as '
                    'active. Unselect this instead of deleting accounts.'))
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        abstract = True
        ordering = ['email']

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.email

    def email_user(self, subject, message, from_email=None, **kwargs):
        # send_mail(subject, message, from_email, [self.email], **kwargs)
        send_mail(subject, message, from_email, self.email, **kwargs)


class AbstractNamedUser(AbstractEmailUser):
    name = models.CharField(_('name'), max_length=255)

    REQUIRED_FIELDS = ['name']

    class Meta:
        abstract = True
        ordering = ['name', 'email']

    def __str__(self):
        return '{name} <{email}>'.format(
            name=self.name,
            email=self.email,
        )

    def get_full_name(self):
        return self.name

    def get_short_name(self):
        return self.name


class User(AbstractNamedUser):





    USER, MODERATOR, ADMIN, BLOG = range(4)
    TYPE_CHOICES = [(USER, "User"), (MODERATOR, "Moderator"), (ADMIN, "Admin"), (BLOG, "Blog")]

    NEW_USER, TRUSTED, SUSPENDED, BANNED = range(4)
    STATUS_CHOICES = ((NEW_USER, 'New User'), (TRUSTED, 'Trusted'), (SUSPENDED, 'Suspended'), (BANNED, 'Banned'))

    USERNAME_FIELD = 'email'

    objects = LocalManager()

    email = models.EmailField(verbose_name='Email', db_index=True, max_length=255, unique=True)
    name = models.CharField(verbose_name='Name', max_length=255, default="", blank=False)

    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    type = models.IntegerField(choices=TYPE_CHOICES, default=USER)
    status = models.IntegerField(choices=STATUS_CHOICES, default=NEW_USER)
    new_messages = models.IntegerField(default=0)
    badges = models.IntegerField(default=0)
    score = models.IntegerField(default=0)
    activity = models.IntegerField(default=0)
    flair = models.CharField(verbose_name='Flair', max_length=15, default="")
    site = models.ForeignKey(Site, null=True)

    @property
    def is_moderator(self):
        if self.is_authenticated():
            return self.type == User.MODERATOR or self.type == User.ADMIN
        else:
            return False

    @property
    def is_administrator(self):
        if self.is_authenticated():
            return self.type == User.ADMIN
        else:
            return False

    @property
    def is_trusted(self):
        return self.status == User.TRUSTED

    @property
    def is_suspended(self):
        return self.status == User.SUSPENDED or self.status == User.BANNED

    def get_full_name(self):
        return self.name or self.email

    def get_short_name(self):
        return self.name or self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    def save(self, *args, **kwargs):
        if not self.name:
            self.name = self.email.split("@")[0]

        super(User, self).save(*args, **kwargs)

    @property
    def scaled_score(self):
        return self.score * 10

    def __str__(self):
        return "%s: %s (%s)" % (self.name, self.email, self.id)

    def get_absolute_url(self):
        url = reverse("user-details", kwargs=dict(pk=self.id))
        return url


class EmailList(models.Model):
    email = models.EmailField(verbose_name='Email', db_index=True, max_length=255, unique=True)
    type = models.IntegerField(default=0)
    active = models.BooleanField(default=True)
    date = models.DateTimeField(auto_created=True)



class Profile(models.Model):
    LOCAL_MESSAGE, EMAIL_MESSAGE = const.LOCAL_MESSAGE, const.EMAIL_MESSAGE
    NO_DIGEST, DAILY_DIGEST, WEEKLY_DIGEST, MONTHLY_DIGEST = range(4)
    TYPE_CHOICES = const.MESSAGING_TYPE_CHOICES

    DIGEST_CHOICES = [(NO_DIGEST, 'Never'), (DAILY_DIGEST, 'Daily'),
                      (WEEKLY_DIGEST, 'Weekly'), (MONTHLY_DIGEST, 'Monthly')]
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    uuid = models.CharField(null=False, db_index=True, unique=True, max_length=255)
    last_login = models.DateTimeField()
    date_joined = models.DateTimeField()
    location = models.CharField(default="", max_length=255, blank=True)
    website = models.URLField(default="", max_length=255, blank=True)
    scholar = models.CharField(default="", max_length=255, blank=True)
    twitter_id = models.CharField(default="", max_length=255, blank=True)
    my_tags = models.TextField(default="", max_length=255, blank=True)
    info = models.TextField(default="", null=True, blank=True)
    message_prefs = models.IntegerField(choices=TYPE_CHOICES, default=MESSAGE_PREFS)
    flag = models.IntegerField(default=0)
    watched_tags = models.CharField(max_length=100, default="", blank=True)
    tags = models.ManyToManyField(Tag, blank=True, )
    digest_prefs = models.IntegerField(choices=DIGEST_CHOICES, default=WEEKLY_DIGEST)
    opt_in = models.BooleanField(default=False)

    def parse_tags(self):
        return util.split_tags(self.tag_val)

    def clear_data(self):
        self.website = self.twitter_id = self.info = self.location = ''
        self.save()

    def add_tags(self, text):
        text = text.strip()
        self.tag_val = bleach.clean(text, tags=[], attributes=[], styles={}, strip=True)
        self.tags.clear()
        tags = [Tag.objects.get_or_create(name=name)[0] for name in self.parse_tags()]
        self.tags.add(*tags)

    def save(self, *args, **kwargs):
        self.info = bleach.clean(self.info, tags=ALLOWED_TAGS,
                                 attributes=ALLOWED_ATTRIBUTES, styles=ALLOWED_STYLES)
        self.location = self.location.strip()
        if not self.id:
            try:
                self.uuid = util.make_uuid()
            except:
                x = random.getrandbits(256)
                return x
            self.date_joined = self.date_joined or now()
            self.last_login = self.date_joined

        super(Profile, self).save(*args, **kwargs)

    def __str__(self):
        return "%s" % self.user.name

    @property
    def filled(self):
        has_location = bool(self.location.strip())
        has_info = bool(self.info.strip())
        return has_location and has_info

    @staticmethod
    def auto_create(sender, instance, created, *args, **kwargs):
        pass
        # "Should run on every user creation."
        # if created:

askcomrade/server/templates/badge_details.html
{% extends "starbase.html" %}
{% load server_tags %}
{% load humanize %}

{% block page_title %}
    Badge: {{ badge.name }}
{% endblock %}

{% block content %}

    <div class="row">

        <div class="col-md-12">
            <h3>Badge: {{ badge.name }} <i class="{{ badge.icon }}"></i> &bull; <a
                    href="{% url 'badge-list' %}">All &raquo;</a></h3>

            <h4>Awarded {{ badge.count }} time{{ badge.count|pluralize }} for: <em>{{ badge.desc }}</em></h4>

            <h4>Recently awarded to </h4>

            {% for award in awards %}

                <div class="col xs-3 col-md-2 text-center" style="height:250px;">
{#isaac                    <div>{% gravatar award.user 82 %}</div>#}
                    <div class="ago">{{ award.date|time_ago }} to</div>
                    <div class="uname">{% userlink award.user %}</div>
                    <div class="loc">{{ award.user.profile.location }}</div>
                    {% if award.context %}
                        <div class="">For: {{ award.context|safe|truncatechars:50 }}</div>
                    {% endif %}
                </div>

            {% endfor %}

        </div>

{% endblock %}

askcomrade/server/templates/badge_list.html
{% extends "starbase.html" %}
{% load server_tags %}
{% load humanize %}

{% block page_title %}
    Badge List
{% endblock %}

{% block content %}


    <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            <h4>Badge list</h4>
        </div>
        <div class="col-xs-8 col-xs-offset-2">
            <table class="table">
                {% for badge in badges %}
                    <tr>
                        <td>
                            <a href="{% url 'badge-view' pk=badge.id %}" class="tag">
                                {{ badge.name }} <i class="{{ badge.icon }}"></i></a> &times; {{ badge.count }}
                        </td>
                        <td>
                            {{ badge.desc }}</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>

{% endblock %}

askcomrade/server/templates/email_list_form.html
{% extends "starbase.html" %}
{% load server_tags %}
{% load humanize %}
{% load crispy_forms_tags %}

{{ SITE_DOMAIN }}Email list subscription

{% block content %}

    <div class="row">

        <div class="col-md-4 col-md-offset-4">
            <h2>Update Email List Settings</h2>
            {% crispy form %}
        </div>

    </div>

{% endblock %}

askcomrade/server/templates/footer.html
 <div class="row toc" style="color: black;">

            <div class="col-xs-3 col-xs-offset-1 col-md-2 col-md-offset-3">
            <div class="title">Content</div>
                <ul class="flat">
                    <li><a href="{% url 'user-list' %}">user-list</a></li>
                    <li><a href="{% url 'badge-list' %}">badge-list</a></li>
                </ul>
            </div>
            <div class="col-xs-3 col-md-2">
                <div class="title">side2</div>
                <ul class="flat">
                    <li><a href="{% url 'user-votes' %}">user-votes</a></li>
                    <li><a href="{% url 'planet' %}">planet</a></li>
                    <li><a href="{% url 'planet-feed' %}">planet-feed</a></li>

                </ul>
            </div>
            <div class="col-xs-3 col-md-2 ">
                <div class="title">side3</div>
                <ul class="flat">
                    <li><a href="{% url 'latest-feed' %}">latest-feed</a></li>
                    <li><a href="{% url 'rss' %}">rss</a></li>
                </ul>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <hr>
            </div>
        </div>

askcomrade/server/templates/message_list.html
{% extends "starbase.html" %}
{% load server_tags %}
{% load humanize %}

{% block content %}

    {% search_bar %}
    {% page_bar %}
    <div class="row">
        <div class="col-md-9">
            {% for message in objects %}
                <div class="stripe unread wrapped {{ message.unread }}">
                    {{ message.sent_at|timesince }} ago: {{ message.body.text|safe }}
                </div>
            {% endfor %}
        </div>
        <div class="col-md-3 sidebar">
            <div class="head">Messages by</div>
            {% sidebar_users people %}
        </div>
    </div>
    {#  this will reset the user unread messages #}
    {% messages_read user %}
{% endblock %}

askcomrade/server/templates/pagedown_widget.html
<div class="">
    <div class="wmd-panel">
        <div id="wmd-button-bar"></div>
         <textarea class="wmd-input" id="wmd-input" name="content" rows="{{ rows }}"
                   placeholder="Type your post here">{{ value }}</textarea>
    </div>
</div>

<div>
    <div id="wmd-preview" class="wmd-panel wmd-preview"></div>
</div>

askcomrade/server/templates/post_moderation_form.html
{% load humanize %}
{% load crispy_forms_tags %}
<div class="alert alert-warning">

    <h4>Moderating {{ post.get_type_display }}: {{ post.title }}</h4>

    {% crispy form %}

</div>

askcomrade/server/templates/site_description.html
 Welcome to Askcomrade

askcomrade/server/templates/user_details.html
{% extends "starbase.html" %}
{% load cache %}
{% load server_tags %}
{% load humanize %}
{% load socialaccount %}

{% block page_title %}
    User: {{ target.name }}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12 user-details">
            <div class="col-md-12">
                <h2 class="text-center {{ target.get_status_display }}">
                    {{ target.get_type_display }}: {{ target.name }}</h2>
            </div>
            <div class="col-md-3">
                <div class="text-center">
                      User gravatar.
{#isaac                  {% gravatar target 200 %}#}
                    <div>{% userlink target %}</div>
                </div>
                <div class="text-center" style="margin-top:20px">
                    {% if target.is_editable and user.is_moderator and user != target %}
                        <div style="margin-top:10px;">
                            <a role="button" class="btn btn-warning mod-user" data-value="{{ target.id }}">Moderate
                                User</a>
                        </div>
                    {% endif %}
                </div>
                {% if target.has_ownership %}
                    <div style="font-size: smaller; padding:0px 0px 20px 20px;">
                        Your portrait is loaded from <a href="http://www.gravatar.com">Gravatar</a> based
                        on your email. If you don't have a <a href="http://www.gravatar.com">Gravatar</a> account
                        your portait is
                        an "identicon": an automatically generated, unique image.
                    </div>
                {% endif %}
            </div>
            {#  The short description entered by the user.  #}
            <div class="col-md-4">
                <dl class="dl-horizontal">


                    <dt>Reputation:</dt>
                    <dd><b>{{ target.scaled_score |intcomma }}</b></dd>

                    <dt>Status:</dt>
                    <dd>{{ target.get_status_display }}</dd>

                    {% if target.score > 0 or user.is_moderator %}
                        <dt>Location:</dt>
                        <dd>{{ target.profile.location }}</dd>



                        {% if target.profile.website %}
                            <dt>Website:</dt>
                            <dd>

                                <a rel="nofollow" href="{{ target.profile.website }}">
                                    {{ target.profile.website|truncatechars:25 }}</a>

                            </dd>
                        {% endif %}
                    {% endif %}


                    {% if target.profile.twitter_id %}
                        <dt>Twitter:</dt>
                        <dd>

                            <i class="fa fa-twitter"></i> <a rel="nofollow"
                                                             href="http://twitter.com/{{ target.profile.twitter_id }}">
                            {{ target.profile.twitter_id|truncatechars:25 }}</a>

                        </dd>
                    {% endif %}

                    {% if target.profile.scholar %}
                        <dt>Scholar ID:</dt>
                        <dd>
                            <a rel="nofollow"
                               href="http://scholar.google.com/citations?user={{ target.profile.scholar }}">Google
                                Scholar Page</a>
                        </dd>
                    {% endif %}
                    <dt>Last seen:</dt>
                    <dd>{{ target.profile.last_login|naturaltime }}</dd>

                    <dt>Joined:</dt>
                    <dd>{{ target.profile.date_joined|naturaltime }}</dd>

                    <dt>Email:</dt>
                    {% if target.has_ownership %}
                        <dd>{{ target.email }}</dd>
                    {% else %}
                        <dd>{{ target.email|hide_email }}</dd>
                    {% endif %}


                    {% if target.has_ownership %}

                        <dt>My Tags:</dt>
                        <dd>{{ target.profile.my_tags|truncatechars:25 }}</dd>

                        <dt>Watched Tags:</dt>
                        <dd>
                            {% for tag in target.profile.tags.all %}
                                {{ tag.name }},
                            {% endfor %}
                        </dd>

                        <dt>Notifications:</dt>
                        <dd>{{ target.profile.get_message_prefs_display }}</dd>


                        <dt>Log in options:</dt>
                        <dd>
                            <a role="button" class="btn btn-info btn-xs" href="{% url 'socialaccount_connections' %}">
                                Social Login</a>
                        </dd>

                        <dt style="margin-top:5px;">
                            Profile settings:
                        </dt>
                        <dd style="margin-top:5px;">
                            <a href="{% url "user-edit" target.id %}" class="btn btn-success btn-xs" role="button"
                               href="#">Edit
                                Your Profile</a>
                        </dd>

                        {% if orcid_profile_url and orcid_id %}
                            <dt style="margin-top:5px;">
                                ORCID profile:
                            </dt>
                            <dd style="margin-top:5px;">
                                <a href="{{ orcid_profile_url }}">{{ orcid_id }}</a>
                            </dd>
                        {% endif %}
                    {% endif %}
                </dl>
            </div>

            {#  User bio.  #}
            <div class="col-md-5">

                {% if target.score > 0 or user.is_moderator %}
                    {{ target.profile.info|safe }}
                {% else %}
                    <p>
                        Profile information, website and location are
                        not shown for new users.
                    </p>
                    <p>
                        This helps us discourage the inappropriate use of our site.
                    </p>
                {% endif %}

            </div>

            {#  Post list goes here #}
            <div class="col-md-12">
                <h4 class="text-center">Posts by {{ target.name }}</h4>
                {% page_bar %}
            </div>
            <div class="col-md-12">
                <div id="post-list">
                    {% for post in posts %}
                        {% post_count_box post post.peek %}
                        {% empty %}

                        <div class="alert alert-info">There are no results for this page.</div>

                    {% endfor %}
                </div>
            </div>

            {% cache 500 "award" target.id %}
                {#  Award list goes here #}
                <div class="col-md-12">
                    <h4 class="text-center">Latest awards to {{ target.name }}</h4>
                </div>
                <div class="col-md-12">
                    <div id="award-list">
                        {% for award in awards %}
                            <div class="col-xs-4 award">

                                <a href="{% url "badge-view" award.badge.id %}">{{ award.badge.name }}
                                    <i class="{{ award.badge.icon }}"></i></a>
                                <span class="ago">{{ award.date|time_ago }}</span>,
                                {{ award.badge.desc }}.
                                {% if award.context %}
{#                                    For {{ award.context|truncatechars:60 }}#}
                                {% endif %}

                            </div>
                            {% empty %}
                            <div class="alert alert-info">No awards yet. Soon to come :-)</div>
                        {% endfor %}
                    </div>
                </div>
            {% endcache %}
        </div>
    </div>

{% endblock %}

askcomrade/server/templates/user_edit.html
{% extends "starbase.html" %}
{% load server_tags %}
{% load humanize %}
{% load crispy_forms_tags %}
{% load static %}

{% block page_title %}
    User Edit
{% endblock %}

{% block content %}

    <div class="row">

        <div class="col-md-8 col-md-offset-2">
          <br>
          {% crispy form %}

        </div>
    </div>

    <script src="{% static 'ckeditor/ckeditor.js' %}"></script>
    <script>
        CKEDITOR.replace('id_info', {
            customConfig: '{% static 'ck_config-v2.js'%}
        });
    </script>
{% endblock %}

askcomrade/server/templates/user_moderation_form.html
{% load humanize %}
{% load crispy_forms_tags %}
<div class="alert alert-warning">

    <h4>Moderate: {{ target.name }}</h4>

    {% crispy form %}

</div>

askcomrade/server/templates/vote_list.html
{% extends "starbase.html" %}
{% load server_tags %}
{% load humanize %}

{% block content %}

    {% search_bar %}

    <div class="row">
        <div class="col-md-9">
            {% page_bar %}
            <table id="posts" class="table table-striped">
                {% for vote in votes %}
                    <tr>
                        <td>
                            {{ vote.get_type_display }}, {{ vote.date|timesince }} ago for
                            the {{ vote.post.get_type_display|lower }}: <a
                        href="{{ vote.post.get_absolute_url }}">{{ vote.post.title }}</a>
                        </td>
                    </tr>

                {% endfor %}
            </table>
            {% page_bar %}
        </div>
        <div class="col-md-3 sidebar">
            <div class="head">People voting on your posts</div>
            {% sidebar_users people %}

        </div>
    </div>
{% endblock %}